name: landingzone

variables:
- name: pipelineCustomVersion
  value: 1.0.0
- template: pipeline.environment.yaml 

trigger:
  batch: true
  branches:
    include:
    - $(branchname)

resources:
  repositories:
  - repository: components
    type: github
    ref: $(branchname)
    endpoint: (connection name)
    name: (Repository Path)

stages:
  - stage:  Deployment
    displayName:  Deployment
    jobs:
    - template: PolicyInitiativePipeline.yaml
      parameters:
        connectionService: 
        - $(connectionService)
        managementGroupName: $(managementgroupname)        
        deploymentBlocks:
        - path: /GIS_Azure_Landingzone_Components/Policies/Initiative
          displayname: InitiativeforResourceDiagnostics
          initiative: DiagInitiative.json
