  
parameters:
  rootFolder: $(System.DefaultWorkingDirectory)/
  # Definition location references management group of the initiative (tenant root group for delivery)
  folderName: "Assignments"
  connectionService: ''
  deploymentBlocks: ''
  managementgroupname: $(managementGroupName)
  definitionLocation: $(definitionLocation)
    
jobs:
- ${{ each connectionService in parameters.connectionService }}:
  - ${{ each deploymentBlock in parameters.deploymentBlocks }}:
    - deployment: '${{ deploymentBlock.DisplayName }}'
      pool:
        vmImage: vs2017-win2016
      environment: env1
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
              - checkout: components                
              - task: AzurePowerShell@4
                displayName: "Create Assignments"
                inputs:
                  azureSubscription: '${{ connectionService }}'
                  ScriptPath: "$(Build.SourcesDirectory)/GIS_Azure_Landingzone_Pipeline/Scripts/Create-PolicyAssignment.ps1"
                  ScriptArguments: 
                    -rootFolder '${{ parameters.rootFolder }}'
                    -assignmentNames '${{ deploymentBlock.path }}/${{ deploymentBlock.policy }}'
                    -definitionLocation '${{ parameters.definitionLocation }}'
                    -managementgroupname '${{ parameters.managementgroupname }}'
                  azurePowerShellVersion: LatestVersion
